name: Cargo tests
on: [push, pull_request]

jobs:
  cargo-tests:
    name: Cargo tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Run cargo test, features = ["build"]
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --features build

    - name: Run cargo test, features = ["build", "enable-openssl"]
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --features build,enable-openssl

    - name: Run cargo test, features = ["build", "build-openssl"]
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --features build,build-openssl
